### ISSUE TITLE
这个是集成滴滴Booster的项目吗？

### ISSUE THREAD

**Issue by 9468305** [Omooo/Booster#1]
rt

**Comment by Omooo** [comment]
并不是撒，只是抄 Booster 的框架然后自己写～
看了一下他写的 list-permission，还没我写的简洁（啊哈哈哈隔逃～
后面的一些模块也自己先写，写不出来抄他的，或者 Matrix，刺激～

最开始用的 KTS 构建，但是 KTS 坑太多了，也可能我太弱鸡了，我又切回来 Groovy 了。。

**Comment by 9468305** [comment]
kts......坚持一下就挺过去了。

**Comment by Omooo** [comment]
留下了弱鸡的眼泪～
